- name: call common role
  debug:
    msg: "Hi, i am from call role msg -1"

- name: call common role
  debug:
    msg: "Hi, i am from call role msg -2"

- name: call common role
  debug:
    msg: "Hi, i am from call role msg -3"
           
- name: call role 2
  import_role:
    name: role-3          